In [1]:
import numpy as np

In [2]:
x = np.array([12, 8, 29, 10])
x

array([12,  8, 29, 10])

### L1 Norm

In [6]:
int(np.abs(12) + np.abs(8) + np.abs(29) + np.abs(10))

59

### Squared L2 Norm - Like L2 Norm but don't have the Sqrt. 

In [7]:
(12**2) + (8**2) + (29**2) + (10**2)

1149

In [9]:
int(np.dot(x, x))

1149

### Max Norm

In [11]:
int(np.max([np.abs(12), np.abs(8), np.abs(29), np.abs(10)]))

29

### Orthogonal vectors

In [12]:
i = np.array([1, 0])
i

array([1, 0])

In [13]:
j = np.array([0, 1])
j

array([0, 1])

In [15]:
int(np.dot(i, j))

0