In [1]:
import numpy as np

In [9]:
x = np.array([12, 8, 92])
x

array([12,  8, 92])

In [3]:
x = np.array([12, 8, 92], dtype=np.float16)
x

array([12.,  8., 92.], dtype=float16)

In [4]:
x = np.array([12, 8, 92], dtype=np.float32)
x

array([12.,  8., 92.], dtype=float32)

In [5]:
y = np.array([12, 8, 92], dtype=np.float64)
y

array([12.,  8., 92.])

In [6]:
z = np.array([12, 8, 92], dtype=np.float64)
z

array([12.,  8., 92.])

In [7]:
# a = np.array([12, 8, 92], dtype=np.float96)
# a

In [8]:
# b = np.array([12, 8, 92], dtype=np.float128)
# b

####Transpose of a vector

In [10]:
x_t = x.T
x_t

array([12,  8, 92])