In [ ]:
%pip install numpy
%pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np

In [ ]:
x = np.array([12, 8, 92])
x

array([12,  8, 92])

In [1]:
x = np.array([12, 8, 92], dtype=np.float16)
x

array([12.,  8., 92.], dtype=float16)

In [7]:
x = np.array([12, 8, 92], dtype=np.float32)
x

array([12.,  8., 92.], dtype=float32)

In [8]:
y = np.array([12, 8, 92], dtype=np.float64)
y

array([12.,  8., 92.])

In [9]:
z = np.array([12, 8, 92], dtype=np.float64)
z

array([12.,  8., 92.])

In [10]:
a = np.array([12, 8, 92], dtype=np.float96)
a

AttributeError: module 'numpy' has no attribute 'float96'

In [11]:
b = np.array([12, 8, 92], dtype=np.float128)
b

AttributeError: module 'numpy' has no attribute 'float128'